!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 2
allowAdventureTwerking: false
chance: 0.5
debug: false
enableAE2Accelerator: true
enableDirtToGrass: false
enableMysticalCrops: false
hoeTakesDamage: false
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:short_grass',
  'minecraft:tall_grass', 'minecraft:netherrack', 'minecraft:warped_nylium', 'minecraft:crimson_nylium',
  '#mysticalagriculture:crops', 'minecraft:seagrass', 'minecraft:moss_block', 'minecraft:pink_petals',
  'irregular_implements:pitcher_plant']
randomTickMultiplier: 4
range: 3
requireHoe: false
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: []
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 2
useWhitelist: false
