[general]
	#List of items to force-allow placing in the belt. Takes precedence over blacklist.
	whitelist = []
	#List of items to disallow from placing in the belt. (whitelist takes precedence)
	blacklist = [
  "simplyswords:frostfall",
  "simplyswords:icewhisper",
  "simplyswords:caelestis",
  "simplyswords:magiscythe",
  "simplyswords:storms_edge",
  "simplyswords:soulpyre",
  "simplyswords:molten_edge",
  "simplyswords:magiblade",
  "simplyswords:bramblethorn",
  "simplyswords:shadowsting",
  "simplyswords:soulstealer",
  "simplyswords:awakened_lichblade",
  "simplyswords:slumbering_lichblade",
  "simplyswords:toxic_longsword",
  "simplyswords:chompolotl",
  "simplyswords:hiveheart",
  "simplyswords:sunfire",
  "simplyswords:thunderbrand",
  "simplyswords:whisperwind",
  "simplyswords:watching_warglaive",
  "simplyswords:decaying_relic",
  "simplyswords:righteous_relic",
  "simplyswords:magispear",
  "simplyswords:waxweaver",
  "simplyswords:tainted_relic",
  "simplyswords:waking_lichblade",
  "simplyswords:hearthflame",
  "simplyswords:flamewind",
  "simplyswords:tempest",
  "simplyswords:arcanethyst",
  "simplyswords:soulrender",
  "simplyswords:harbinger",
  "simplyswords:stormbringer",
  "simplyswords:emberblade",
  "simplyswords:watcher_claymore",
  "simplyswords:enigma",
  "simplyswords:emberlash",
  "simplyswords:twisted_blade",
  "simplyswords:soulkeeper",
  "simplyswords:wraithfang",
  "simplyswords:brimstone_claymore",
  "simplyswords:ribboncleaver",
  "simplyswords:livyatan",
  "simplyswords:dormant_relic",
  "simplyswords:mjolnir",
  "simplyswords:wickpiercer",
  "simplyswords:stars_edge",
  "sophisticatedbackpacks:backpack",
  "sophisticatedbackpacks:copper_backpack",
  "sophisticatedbackpacks:iron_backpack",
  "sophisticatedbackpacks:gold_backpack",
  "sophisticatedbackpacks:diamond_backpack",
  "sophisticatedbackpacks:netherite_backpack"
]

	#When set to false, stackable items will no longer be allowed by default.
	allowAllNonStackableItems = true


